version: '3.8'

services:
  evolution_db:
    image: postgres:15-alpine
    container_name: evolution_db
    restart: always
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: coecaribe_user
      POSTGRES_PASSWORD: DBPasswordSecure2026
    volumes:
      - evolution_db_data:/var/lib/postgresql/data

  evolution_api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_URL=http://167.88.45.94:8080
      # Configuración de Seguridad y API Key
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=ClinicaCoecaribe2026
      - API_KEY=ClinicaCoecaribe2026
      # Configuración de Base de Datos
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://coecaribe_user:DBPasswordSecure2026@evolution_db:5432/evolution?schema=public
      # Configuración de Caché
      - CACHE_REDIS_ENABLED=false
      - CACHE_LOCAL_ENABLED=true
      # Deshabilitar temporales
      - DEL_INSTANCE_TEMP_FOLDER=true
    depends_on:
      - evolution_db

volumes:
  evolution_db_data:
